# Generated by Django 4.2 on 2026-03-27 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ForexData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("open_price", models.DecimalField(decimal_places=5, max_digits=10)),
                ("high_price", models.DecimalField(decimal_places=5, max_digits=10)),
                ("low_price", models.DecimalField(decimal_places=5, max_digits=10)),
                ("close_price", models.DecimalField(decimal_places=5, max_digits=10)),
                ("volume", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ForexPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["symbol"],
            },
        ),
        migrations.CreateModel(
            name="TradingSignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "signal_type",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell"), ("HOLD", "Hold")],
                        max_length=10,
                    ),
                ),
                ("confidence", models.FloatField()),
                ("reason", models.TextField()),
                (
                    "price_at_signal",
                    models.DecimalField(decimal_places=5, max_digits=10),
                ),
                ("rsi_value", models.FloatField(blank=True, null=True)),
                ("macd_value", models.FloatField(blank=True, null=True)),
                (
                    "greed_level",
                    models.CharField(
                        choices=[
                            ("extreme_greed", "Extreme Greed"),
                            ("greed", "Greed"),
                            ("neutral", "Neutral"),
                            ("fear", "Fear"),
                            ("extreme_fear", "Extreme Fear"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "pair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signals",
                        to="analyzer.forexpair",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="TechnicalIndicators",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rsi", models.FloatField(blank=True, null=True)),
                (
                    "rsi_signal",
                    models.CharField(
                        choices=[
                            ("overbought", "Overbought"),
                            ("normal", "Normal"),
                            ("oversold", "Oversold"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                ("macd", models.FloatField(blank=True, null=True)),
                ("macd_signal", models.FloatField(blank=True, null=True)),
                ("macd_histogram", models.FloatField(blank=True, null=True)),
                ("sma_20", models.FloatField(blank=True, null=True)),
                ("sma_50", models.FloatField(blank=True, null=True)),
                (
                    "forex_data",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicators",
                        to="analyzer.forexdata",
                    ),
                ),
            ],
            options={
                "ordering": ["-forex_data__timestamp"],
            },
        ),
        migrations.AddField(
            model_name="forexdata",
            name="pair",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data",
                to="analyzer.forexpair",
            ),
        ),
        migrations.AddIndex(
            model_name="forexdata",
            index=models.Index(
                fields=["pair", "-timestamp"], name="analyzer_fo_pair_id_b29cbb_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="forexdata",
            unique_together={("pair", "timestamp")},
        ),
    ]
